/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Absence } from '../../models/absence';

export interface ApiAbsencesUserUserIdGet$Json$Params {
  userId: string;
}

export function apiAbsencesUserUserIdGet$Json(http: HttpClient, rootUrl: string, params: ApiAbsencesUserUserIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Absence>>> {
  const rb = new RequestBuilder(rootUrl, apiAbsencesUserUserIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Absence>>;
    })
  );
}

apiAbsencesUserUserIdGet$Json.PATH = '/api/absences/user/{userId}';
