/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Absence } from '../../models/absence';
import { CreateAbsenceDto } from '../../models/create-absence-dto';

export interface ApiAbsencesPost$Plain$Params {
      body?: CreateAbsenceDto
}

export function apiAbsencesPost$Plain(http: HttpClient, rootUrl: string, params?: ApiAbsencesPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Absence>> {
  const rb = new RequestBuilder(rootUrl, apiAbsencesPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Absence>;
    })
  );
}

apiAbsencesPost$Plain.PATH = '/api/absences';
