/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Absence } from '../../models/absence';
import { UpdateAbsenceDto } from '../../models/update-absence-dto';

export interface ApiAbsencesIdPut$Json$Params {
  id: string;
      body?: UpdateAbsenceDto
}

export function apiAbsencesIdPut$Json(http: HttpClient, rootUrl: string, params: ApiAbsencesIdPut$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Absence>> {
  const rb = new RequestBuilder(rootUrl, apiAbsencesIdPut$Json.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Absence>;
    })
  );
}

apiAbsencesIdPut$Json.PATH = '/api/absences/{id}';
