/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Absence } from '../../models/absence';
import { AbsenceStatus } from '../../models/absence-status';

export interface ApiAbsencesGet$Json$Params {
  userId?: string;
  status?: AbsenceStatus;
  from?: string;
  to?: string;
}

export function apiAbsencesGet$Json(http: HttpClient, rootUrl: string, params?: ApiAbsencesGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Absence>>> {
  const rb = new RequestBuilder(rootUrl, apiAbsencesGet$Json.PATH, 'get');
  if (params) {
    rb.query('userId', params.userId, {});
    rb.query('status', params.status, {});
    rb.query('from', params.from, {});
    rb.query('to', params.to, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Absence>>;
    })
  );
}

apiAbsencesGet$Json.PATH = '/api/absences';
