/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Absence } from './models/absence';
export type { AbsenceStatus } from './models/absence-status';
export type { AbsenceType } from './models/absence-type';
export type { Company } from './models/company';
export type { CreateProjectDto } from './models/create-project-dto';
export type { CreateTimeEntryDto } from './models/create-time-entry-dto';
export type { EmploymentContract } from './models/employment-contract';
export type { LoginDto } from './models/login-dto';
export type { Project } from './models/project';
export type { ProjectAddress } from './models/project-address';
export type { ProjectAddressDto } from './models/project-address-dto';
export type { RegisterCompanyDto } from './models/register-company-dto';
export type { RegisterUserDto } from './models/register-user-dto';
export type { Role } from './models/role';
export type { TimeEntry } from './models/time-entry';
export type { UpdateProjectDto } from './models/update-project-dto';
export type { UpdateUserDto } from './models/update-user-dto';
export type { User } from './models/user';
