/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TimeEntry } from '../../models/time-entry';

export interface ApiTimeEntriesProjectProjectIdGet$Json$Params {
  projectId: string;
  from?: string;
  to?: string;
}

export function apiTimeEntriesProjectProjectIdGet$Json(http: HttpClient, rootUrl: string, params: ApiTimeEntriesProjectProjectIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TimeEntry>>> {
  const rb = new RequestBuilder(rootUrl, apiTimeEntriesProjectProjectIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('projectId', params.projectId, {});
    rb.query('from', params.from, {});
    rb.query('to', params.to, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TimeEntry>>;
    })
  );
}

apiTimeEntriesProjectProjectIdGet$Json.PATH = '/api/time-entries/project/{projectId}';
