/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TimeEntry } from '../../models/time-entry';
import { UpdateTimeEntryDto } from '../../models/update-time-entry-dto';

export interface ApiTimeEntriesIdPut$Json$Params {
  id: string;
      body?: UpdateTimeEntryDto
}

export function apiTimeEntriesIdPut$Json(http: HttpClient, rootUrl: string, params: ApiTimeEntriesIdPut$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<TimeEntry>> {
  const rb = new RequestBuilder(rootUrl, apiTimeEntriesIdPut$Json.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TimeEntry>;
    })
  );
}

apiTimeEntriesIdPut$Json.PATH = '/api/time-entries/{id}';
