/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateTimeEntryDto } from '../../models/create-time-entry-dto';
import { TimeEntry } from '../../models/time-entry';

export interface ApiTimeEntriesPost$Json$Params {
      body?: CreateTimeEntryDto
}

export function apiTimeEntriesPost$Json(http: HttpClient, rootUrl: string, params?: ApiTimeEntriesPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<TimeEntry>> {
  const rb = new RequestBuilder(rootUrl, apiTimeEntriesPost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TimeEntry>;
    })
  );
}

apiTimeEntriesPost$Json.PATH = '/api/time-entries';
