/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TimeEntry } from '../../models/time-entry';

export interface ApiTimeEntriesUserUserIdGet$Plain$Params {
  userId: string;
  from?: string;
  to?: string;
}

export function apiTimeEntriesUserUserIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiTimeEntriesUserUserIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TimeEntry>>> {
  const rb = new RequestBuilder(rootUrl, apiTimeEntriesUserUserIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.query('from', params.from, {});
    rb.query('to', params.to, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TimeEntry>>;
    })
  );
}

apiTimeEntriesUserUserIdGet$Plain.PATH = '/api/time-entries/user/{userId}';
