/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AbsenceStatus } from './absence-status';

/**
 * Each possible value of `AbsenceStatus`
 */
export const ABSENCE_STATUS: AbsenceStatus[] = [
  0,
  1,
  2,
  3
];