/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AbsenceType } from './absence-type';

/**
 * Each possible value of `AbsenceType`
 */
export const ABSENCE_TYPE: AbsenceType[] = [
  0,
  1,
  2,
  3
];