/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Project } from '../models/project';
import { User } from '../models/user';
export interface Company {
  city?: string | null;
  country?: string | null;
  createdAt?: string;
  houseNumber?: number | null;
  id?: string;
  isActive?: boolean;
  name?: string | null;
  postalCode?: number | null;
  projects?: Array<Project> | null;
  street?: string | null;
  users?: Array<User> | null;
}
