/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectAddressDto } from '../models/project-address-dto';
export interface CreateProjectDto {
  address?: ProjectAddressDto;
  companyId?: string;
  description?: string | null;
  name?: string | null;
}
