/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateTimeEntryDto {
  breakMinutes?: number;
  comment?: string | null;
  date?: string;
  minutesWorked?: number;
  projectId?: string;
}
