/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface EmploymentContract {
  endDate?: string | null;
  id?: string;
  startDate?: string;
  user?: User;
  userId?: string;
  weeklyHours?: number;
}
