/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProjectAddressDto {
  city: string;
  country: string;
  houseNumber?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  postalCode: string;
  street: string;
}
