/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Role } from '../models/role';
export interface RegisterUserDto {
  companyId?: string;
  email: string;
  firstName: string;
  lastName: string;
  password: string;
  role: Role;
}
