/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterCompanyDto {
  adminEmail: string;
  city?: string | null;
  companyName: string;
  country?: string | null;
  firstName: string;
  houseNumber?: number | null;
  lastName: string;
  password: string;
  postalCode?: number | null;
  street?: string | null;
}
