/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterUserDto {
  companyId?: string;
  email?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  password?: string | null;
  role?: number;
}
