/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectAddressDto } from '../models/project-address-dto';
export interface UpdateProjectDto {
  address?: ProjectAddressDto;
  description?: string | null;
  isActive?: boolean;
  name?: string | null;
}
