/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AbsenceType } from '../models/absence-type';
export interface UpdateAbsenceDto {
  attachmentUrl?: string | null;
  endDate?: string;
  startDate?: string;
  type?: AbsenceType;
}
