/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AbsenceStatus } from '../models/absence-status';
export interface UpdateAbsenceStatusDto {
  status?: AbsenceStatus;
}
