/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Role } from '../models/role';
export interface UserResponseDto {
  companyId?: string;
  email?: string | null;
  firstName?: string | null;
  id?: string;
  lastName?: string | null;
  role?: Role;
}
